repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --new-from-rev HEAD --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: go-unit-tests
        name: go unit tests
        entry: go test -short -p=1 ./...
        pass_filenames: false
        types: [go]
        language: system
