# Based on https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish to PyPI
on:
  push:
    tags:
      - "releases/**"

jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Verify tag is annotated
        if: startsWith(github.ref, 'refs/tags')
        run: >-
          echo ${GITHUB_REF}
          git for-each-ref --format='%(objecttype)' ${GITHUB_REF}
          test $(git for-each-ref --format='%(objecttype)' ${GITHUB_REF}) == tag
