# Based on https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish to PyPI
on:
  push:
    tags:
      - "releases/**"

jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: echo ${GITHUB_REF}
      - run: git --version
      - run: git fetch --tags --force
      - run: git for-each-ref --format='%(objecttype)' ${GITHUB_REF}
      - run: git describe --exact-match HEAD
      - run: test $(git for-each-ref --format='%(objecttype)' ${GITHUB_REF}) == tag
